plugins {
    id 'com.android.application'
}

android {
    compileSdk 34
    namespace "com.zoro.ugv"

    defaultConfig {
        applicationId "com.zoro.ugv"
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName "2.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

// Set Java Toolchain to 17 (placed outside android block)
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
